### ISSUE TITLE
能说说怎么通过插件调试吗？

### ISSUE THREAD

**Issue by spysoos** [sanyuankexie/Flexml#58]
能说说怎么通过插件调试吗？另外，能说说项目中各个模块的具体功能或通途吗？
除了插件还需要额外安装其他App吗？希望能简短的说一下过程，谢谢

**Comment by LukeXeon** [comment]
已更新部分doc，希望这里的内容可以帮到你[插件模块README.md](https://github.com/sanyuankexie/Flexml/blob/master/intellij-plugin/README.md)
