### ISSUE TITLE
Banner的indicator如何设置才能显示?

### ISSUE THREAD

**Issue by spysoos** [sanyuankexie/Flexml#59]
请问Banner的indicator如何设置才能显示?
![TIM截图20200222112533](https://user-images.githubusercontent.com/982866/75085625-1aa0ea80-5566-11ea-93ef-f4230effbae8.png)

**Comment by LukeXeon** [comment]
该属性暂时还未生效

**Comment by spysoos** [comment]
OK,非常期待

**Comment by spysoos** [comment]
stack 能做点击效果吗？比如点击改变背景颜色,抬起后恢复原色
