### ISSUE TITLE
这么棒的框架还维护吗？

### ISSUE THREAD

**Issue by spysoos** [sanyuankexie/Flexml#64]
这么棒的框架还维护吗？好久没更新了

**Comment by LukeXeon** [comment]
最近没有时间



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: spysoos <notifications@github.com&gt;
发送时间: 2020年4月16日 16:33
收件人: sanyuankexie/Flexml <Flexml@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[sanyuankexie/Flexml] 这么棒的框架还维护吗？ (#64)





 
这么棒的框架还维护吗？好久没更新了

**Comment by LukeXeon** [comment]
你可以给我发PR

**Comment by spysoos** [comment]
OK
