### ISSUE TITLE
关于Text显示富文本包含超链接的问题

### ISSUE THREAD

**Issue by spysoos** [sanyuankexie/Flexml#70]
Text显示富文本包含超链接时，点击超链接会跳转到手机浏览器。希望框架内部能首先响应点击

**Comment by LukeXeon** [comment]
已经给你开了写权限了，你可以自己合MR，我工作比较忙，已经没有时间在维护这个项目了，祝你好运


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: spysoos <notifications@github.com&gt;
发送时间: 2020年11月24日 12:32
收件人: sanyuankexie/Flexml <Flexml@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[sanyuankexie/Flexml] 关于Text显示富文本包含超链接的问题 (#70)





 
Closed #70.
