### ISSUE TITLE
插件会导致xml标签爆红

### ISSUE THREAD

**Issue by hanjx-dut** [sanyuankexie/Flexml#75]
开启插件后，xml 标签全部标红
![image](https://user-images.githubusercontent.com/62710651/93177503-80083300-f765-11ea-9a43-05ba7ba06a9a.png)
关闭插件重启
![image](https://user-images.githubusercontent.com/62710651/93177611-a9c15a00-f765-11ea-86af-b9b74ecf9d05.png)
我的 Android Studio 版本
![image](https://user-images.githubusercontent.com/62710651/93177675-be055700-f765-11ea-8015-b39cda3dd933.png)
我的mac信息
![image](https://user-images.githubusercontent.com/62710651/93177965-26543880-f766-11ea-8d78-06a32336c6c4.png)

**Comment by callmeli** [comment]
[try this](https://github.com/sanyuankexie/Flexml/pull/73/files)
