### ISSUE TITLE
疑问：出于什么考虑把Banner里 viewpager2修改切换速度的代码去掉了？

### ISSUE THREAD

**Issue by spysoos** [sanyuankexie/Flexml#79]
疑问：出于什么考虑把Banner里 viewpager2修改切换速度的代码去掉了？

**Comment by LukeXeon** [comment]
时间太久记不清了


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: spysoos <notifications@github.com&gt;
发送时间: 2020年12月8日 12:42
收件人: sanyuankexie/Flexml <Flexml@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[sanyuankexie/Flexml] 疑问：出于什么考虑把Banner里 viewpager2修改切换速度的代码去掉了？ (#79)





 
疑问：出于什么考虑把Banner里 viewpager2修改切换速度的代码去掉了？
